### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LiangliangSui** [JohnEsleyer/mp4-to-frames#1]
Hello @JohnEsleyer, have you considered adding the function of playing MP4 frame by frame?

**Comment by JohnEsleyer** [comment]
Hi @LiangliangSui, thank you for your suggestion! If I understand correctly, you are asking about adding a feature to the project that allows for playing an MP4 file frame by frame. This would be a functionality where users can view each frame sequentially, with controls to move forward or backward through the frames. 
If this is what you mean, I appreciate the idea. Adding this feature could indeed be very helpful. I'll add this feature to the project's roadmap and start investigating possible implementations. Thank you again for the suggestion.

**Comment by LiangliangSui** [comment]
Yeah, this is what I want to express.

**Comment by LiangliangSui** [comment]
I am very interested in this project, if possible, I would like to join in.

**Comment by JohnEsleyer** [comment]
If you want to contribute to the project. Feel free to fork the repository and start working with your ideas. Once you have something ready, you can submit a pull requests.
